version: "3.7"

services:
  frontend:
    image: node:10-alpine
    container_name: frontend
    command: sh -c "npm install && npm run serve"
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - mynetwork
  backend:
    image: node:10-alpine
    container_name: backend
    command: sh -c "npm install && node app.js"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

networks:
  mynetwork: